version: '3.3'
services:
  wordpress:
    env_file: .env
    container_name: wp-bedrock
    image: wordpress:php8.2-apache
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress:/var/www/html
volumes:
  wordpress_data:
